[plugins]
shadow = "com.github.johnrengelman.shadow:7.1.2"
spotless = "com.diffplug.spotless:6.17.0"
nukkitPluginYAML = "net.minecrell.plugin-yml.nukkit:0.5.1"

[libraries]
lombok = "org.projectlombok:lombok:1.18.24"
mongodb = "org.mongodb:mongodb-driver-sync:4.8.1"
gson = "com.google.code.gson:gson:2.10.1"
apacheCommons = "org.apache.commons:commons-lang3:3.0"
annotations = "org.jetbrains:annotations:24.0.1"
mot = "cn.nukkit:nukkit:MOT-0.0.2"

miwiklark = "it.bitrule.miwiklark:miwiklark-core:2024.0417.14"
commandapiNukkit = "it.bitrule.plorex.commands:nukkitv2:2024.0106.8"